baseurl = "https://www.corywaters.com/"
languageCode = "en-us"
title = "Questioning Certainty"
theme = "hugo-ivy"
googleAnalytics = "UA-107296047-1"
disqusShortname = "corywaters"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Blog"
    url = "/post/"
[[menu.main]]
    name = "Links"
    url = "/links/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "Talks"
    url = "/talks/"
[[menu.main]]
    name = "Uses"
    url = "/uses/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cswaters"

[params]
    description = "The website of Cory Waters."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "python"]
    highlightjsTheme = "tomorrow"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.jpeg"
    width = 50
    height = 50
    alt = "Logo"

