---
title: Sports Betting Links to Data and Stats
author: cw
date: '2017-05-12'
slug: sports-betting-links-to-data-and-stats
categories:
  - betting
tags:
  - links
  - data
description: 'Links for sports odds and stats.'
---

This post got decent traffic on the old blog. It's the one article that made it to this new version. The title was “Sports Betting Data Downloads” (which wasn’t a good name in hindsight). A quarter of those links are dead, and there’s new material out there. Here's an updated but pared down list.

## Data

### Pay For Data

*note: I don’t make a dime off recommending any of these*

Most of the links are US focused unless otherwise noted.

+ [kostats](http://www.kostats.com) IMO the most extensive sports betting focused database out there. It’s not cheap compared to the other options but I think it’s worth the price if you’re serious and don’t want to do the work. The major US sports (football, basketball, baseball, and hockey) are available. The customer service (if you happen to need it) is great they’ve always gotten back to me within the same day— often within a couple hours. One thing to consider is that kostats isn’t player stat focused so you might need to get the in-depth player stats from somewhere else, but that material is easier to find (see below).
+ [gamblingdbs.com](http://www.gamblingdbs.com) Not as extensive as kostats in some areas but probably the best value for the money. Game stats and odds focused. The NASCAR database is pretty unique. They allow you to update your database at the end of the season for free. There's a in-season update pay-for option.
+ [SportsInsights](https://www.sportsinsights.com/sports-betting-systems/historical-betting-odds-sports-data) The historical odds are now rolled into their BetLabs product.
+ [Armchair Analysis](http://www.armchairanalysis.com) AA is NFL focused product. They have spread and total data for each game. But the real value is the player and play by play data.

### Free Data

Data broken down into two groups.

1. Odds data  - point spreads, money lines, totals, etc.
2. Stats data - points per game, yards per play, shots per game, etc.

Some of the sets can fall into both categories like the SunshineForecast data.
*note:* Some of these datasets haven’t aren't updated but still valuable IMO.

#### Odds Data

* [SunshineForecast](http://www.repole.com/sun4cast/data.html) NFL and NCAA football going back to 1978. Point Spreads and totals for NFL spreads for NCAA. Probably the best free football source on the net. I’ve read in a couple of forums some of the numbers are off. For the price you can’t complain.
* [football-data.co.uk](http://football-data.co.uk/data.php) Major European soccer. 3way lines some AHC and totals. You'll need to click around a bit and save the page as CSV and import but it's free and extensive. 
* [tennis-data.co.uk](http://www.tennis-data.co.uk/data.php) from the same provider as above. Most of the tournaments have at least 5+ years of data. Results, odds from different sportsbooks (euro focused), match details and descriptions [check the notes](http://www.tennis-data.co.uk/notes.txt) file for a breakdown of the data. 

As a side note, [Joseph Buchdahl](http://12xpert.co.uk), provides and maintains the data at [football-data.co.uk](http://football-data.co.uk/data.php) and [tennis-data.co.uk](http://www.tennis-data.co.uk/data.php) free of charge. If you haven't already, you should check out his books on sports betting. The books have a euro-focus but still filled with lots of useful information for US bettors. Cheap way to say thanks for a valuable resource. (Again, I get nothing for the recommendations.)

#### Stats Data

The links below provide either csv, sql, or some other standard form of data for download. No scrapping required.

* [DougStats](http://www.dougstats.com) MLB and NBA game and player data going back to the start of the 90's.
* [Basketball Value]([11](#): http://basketballvalue.com/downloads.php) NBA PxP data 2006 to 2011.
* [Lahman Baseball Database](http://www.seanlahman.com/baseball-archive/statistics/) most comprehensive MLB DB out there. Updated after each season. Available for all formats (csv, sql, as an R package).
* [Retrosheet](http://www.retrosheet.org/) The MLB PxP database.
* [MinorLeagueSplits](http://www.minorleaguesplits.com/x_milb/) Minor league baseball. No longer supported but free downloads offered for 2005-2010 data 
* [NFLsavant.com’s datasets](http://www.nflsavant.com/about.php) A variety of NFL datasets. NFL PxP data 2013 - 2016. NFL combine data. NFL weather data.
* [Seldom used reserve](http://www.seldomusedreserve.com/?page_id=8805) Impressive FBS dataset including box score and odds for all FBS games 2011 - 2016
* [adjusted stats](http://www.adjustedstats.com/ratings-stats/) lot’s of NCAA football data. A little raw, preprocessing is necessary. Goes back to 2000.
* [Brian Burke’s Archived AdvancedFootballAnalytics PxP data](http://archive.advancedfootballanalytics.com/2010/04/play-by-play-data.html) 2002 - 2012.

#### Other: API's and sites to scrape

The following need to be scraped or accessed via an API. You could copy/paste into an excel sheet. But that would be time consuming (I speak from experience).

+ [nflgame](http://pdoc.burntsushi.net/nflgame) from the site: "nflgame is an API to retrieve and read NFL Game Center JSON data. It can work with real-time data." 
+ [mlbgame](http://panz.io/mlbgame/) from the site: "mlbgame is a Python API to retrieve and read MLB GameDay XML data. mlbgame works with real time data, getting information as games are being played."
+ [mlb_terminal](https://github.com/slnovak/mlb_terminal) from the site: "Access to historical and real-time MLB baseball scores and stats in the terminal."
+ [nba_py](https://github.com/seemethere/nba_py) from the site: "A python facing API for stats.nba.com"
+ [jsonodds](https://jsonodds.com) Jsonodds is a paid service. But as far as odds API's it's a cheap as they come. The Rest API is easy to use.
+ [xmlstats](https://erikberg.com/api) Never used the service. You'll need to request an API.
+ [teamrankings.com](https://www.teamrankings.com) Detailed stats (plus odds) for football, baseball, and basketball. It's not difficult to extract the data you need from the site. They do analysis and paid picks for a price.
+ [statfox](http://statfox.com) The original teamrankings format. More written content. statfox offers premium trends and stats for a price.
+ [nbawowy](http://nbawowy.com) Advanced NBA stats
+ [masseyratings](http://www.masseyratings.com/index.htm) Along with the ratings and predictions for US sports there's historical scores and schedules. They're buried so you're going to need to dig. The layout is a mess.


